spring:
  profiles: peer3
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
server:
  port: ${PORT:8673}
eureka:
  instance:
    preferIpAddress: false
    hostname: peer3
    metadataMap:
      zone: zone3
  client:
    service-url:
      defaultZone: http://admin:admin@peer1:8671/eureka/,http://admin:admin@peer2:8672/eureka/
    registerWithEureka: true
    fetchRegistry: true
    #https://www.baeldung.com/spring-cloud-netflix-eureka#transportexception-cannot-execute-request-on-any-known-server
    registryFetchIntervalMs: 3000