spring:
  profiles:
    - zone${SEQUENCE_NO}
  application:
    name: customer-service
server:
  port: 700${SEQUENCE_NO}
eureka:
  instance:
    instanceId: ${spring.application.name}-zone${SEQUENCE_NO}
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 10
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8671/eureka/,http://admin:admin@peer2:8672/eureka/,http://admin:admin@peer3:8673/eureka/
    preferSameZoneEureka: true
order-service:
    ribbon:
      eureka:
       enabled: true
      ServerListRefreshInterval: 15000
management:
  endpoints:
    web:
      exposure:
        include:
          - hystrix.stream #Individual instance stream
#          - turbine.stream #Aggregates all relevant hystrix.stream and healps to monitor the overall health of the system
#turbine:
#  app-config: CUSTOMER-SERVICE
#  aggregator:
#    cluster-config:
#      - CUSTOMER-SERVICE
#order-service:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:7000,localhost:7001
#    ServerListRefreshInterval: 15000
#Named client for the list of servers: “order-service”
#Disabled Eureka service discovery component, by setting eureka: enabled to false
#Defined the list of servers available for load balancing, in this case, 2 servers
#Configured the server refresh rate with ServerListRefreshInterval
