spring:
  profiles:
    - zone${SEQUENCE_NO}
  application:
    name: order-service
server:
  port: 600${SEQUENCE_NO}

eureka:
  instance:
    instanceId: ${spring.application.name}-zone${SEQUENCE_NO}
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8671/eureka/,http://admin:admin@peer2:8672/eureka/,http://admin:admin@peer3:8673/eureka/
    preferSameZoneEureka: true

logging:
  level:
    web: info
    root: info