spring:
  application:
    name: product-service
server:
  port: ${product.service.port}
eureka:
  instance:
    instanceId: ${spring.application.name}-${SEQUENCE_NO}
  client:
    registryFetchIntervalSeconds: 3
    shouldDisableDelta: true
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8671/eureka/,http://admin:admin@peer2:8672/eureka/,http://admin:admin@peer3:8673/eureka/
#order-service:
#  ribbon:
#    eureka:
#      enabled: false
#    listOfServers: localhost:7000,localhost:7001
#    ServerListRefreshInterval: 15000
#Named client for the list of servers: “order-service”
#Disabled Eureka service discovery component, by setting eureka: enabled to false
#Defined the list of servers available for load balancing, in this case, 2 servers
#Configured the server refresh rate with ServerListRefreshInterval
